---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple
spec:
  version:
    kafka_version: 2.8.0
  zookeeperReference:
    namespace: default
    name: simple
  brokers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/arch: stackable-linux
        replicas: 1
        config:
          logDirs: "/tmp/kafka-logs"
          metricsPort: 9606