---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkCluster
metadata:
  name: simple
spec:
  version: "3.0.1"
  config:
    logDir: "file:///data/spark/logs"
    enableMonitoring: true
  masters:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: stackable-linux
        replicas: 1
        config:
          masterPort: 7078
          masterWebUiPort: 8081
  workers:
    roleGroups:
      2core2g:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/arch
              values:
                - stackable-linux
        replicas: 1
        config:
          cores: 2
          memory: "2g"
          workerPort: 3031
          workerWebUiPort: 8083
  historyServers:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/arch
              values:
                - stackable-linux
        replicas: 1
        config:
          historyWebUiPort: 18081
