---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple
spec:
  version: 3.5.8
  servers:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/arch
              values:
                - stackable-linux
        replicas: 1
        config:
          adminPort: 12000
          metricsPort: 9505
          dataDir: /data/zookeeperq